import type { PersonType } from '../../customers/domain/customer-enums';
import type { FieldConfig, FormConfiguration, SectionConfig } from '../domain/form-metadata.types';

const customerSections: SectionConfig[] = [
  {
    key: 'profile',
    label: 'Perfil',
    description: 'Campos principais de identificacao do cliente, variando entre PF e PJ.',
    order: 1,
  },
  {
    key: 'core',
    label: 'Dados Cadastrais',
    description: 'Informacoes comerciais e operacionais comuns ao cadastro.',
    order: 2,
  },
  {
    key: 'financial',
    label: 'Financeiro',
    description: 'Campos financeiros usados para operacao e calculo de lucratividade.',
    order: 3,
  },
  {
    key: 'address',
    label: 'Endereco',
    description: 'Endereco principal do cliente.',
    order: 4,
  },
  {
    key: 'contacts',
    label: 'Contatos',
    description: 'Colecao de contatos telefonicos e de mensagem do cliente.',
    order: 5,
  },
  {
    key: 'emails',
    label: 'Emails',
    description: 'Colecao de e-mails vinculados ao cliente.',
    order: 6,
  },
  {
    key: 'communicationPreferences',
    label: 'Preferencias de Comunicacao',
    description: 'Regras de permissao de envio por canal e assunto.',
    order: 7,
  },
  {
    key: 'responsibles',
    label: 'Responsaveis',
    description: 'Colecao de responsaveis vinculados ao cliente PJ.',
    order: 8,
  },
];

const customerFields: FieldConfig[] = [
  {
    fieldKey: 'personType',
    label: 'Tipo de Pessoa',
    section: 'profile',
    required: true,
    importance: 'HIGH',
    inputType: 'select',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 1,
    visibleWhen: null,
    description: 'Define se o cadastro sera tratado como pessoa fisica ou juridica.',
    businessImpact: 'Controla quais blocos de perfil e regras de validacao serao aplicados pelo sistema.',
    optionsSource: 'static:person-types',
  },
  {
    fieldKey: 'profile.cpf',
    label: 'CPF',
    section: 'profile',
    required: true,
    importance: 'HIGH',
    inputType: 'document',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 2,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Documento principal da pessoa fisica.',
    businessImpact: 'Usado como identificador unico da PF e para buscas por documento.',
    mask: 'cpf',
  },
  {
    fieldKey: 'profile.fullName',
    label: 'Nome Completo',
    section: 'profile',
    required: true,
    importance: 'HIGH',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 3,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Nome completo da pessoa fisica.',
    businessImpact: 'Principal identificador textual do cliente PF em buscas, listagens e indicacoes.',
    placeholder: 'Informe o nome completo',
  },
  {
    fieldKey: 'profile.rg',
    label: 'RG',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'document',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 4,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Documento secundario da pessoa fisica.',
    businessImpact: 'Complementa a identificacao do cadastro quando necessario.',
  },
  {
    fieldKey: 'profile.nickname',
    label: 'Apelido',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 5,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Nome curto, apelido ou nome preferencial do cliente.',
    businessImpact: 'Facilita identificacao operacional e exibicao amigavel no frontend.',
  },
  {
    fieldKey: 'profile.birthDate',
    label: 'Data de Nascimento',
    section: 'profile',
    required: false,
    importance: 'HIGH',
    inputType: 'date',
    dataType: 'date',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 6,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Data de nascimento da pessoa fisica.',
    businessImpact: 'Permite calcular a idade do cliente e suportar regras futuras relacionadas a perfil.',
  },
  {
    fieldKey: 'profile.gender',
    label: 'Sexo',
    section: 'profile',
    required: false,
    importance: 'HIGH',
    inputType: 'select',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 7,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Genero informado no cadastro.',
    businessImpact: 'Serve para perfilizacao e exibicao, sem bloquear operacoes do sistema.',
    optionsSource: 'static:genders',
  },
  {
    fieldKey: 'profile.familyRelationship',
    label: 'Relacao Familiar',
    section: 'profile',
    required: false,
    importance: 'HIGH',
    inputType: 'select',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 8,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Relacao familiar destacada no cadastro.',
    businessImpact: 'Ajuda a contextualizar o cliente no relacionamento comercial.',
    optionsSource: 'static:family-relationships',
  },
  {
    fieldKey: 'profile.profession',
    label: 'Profissao',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 9,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Profissao da pessoa fisica.',
    businessImpact: 'Pode ser usada para analise de perfil comercial ou operacional.',
  },
  {
    fieldKey: 'profile.driverLicenseExpiresAt',
    label: 'CNH Vencimento',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'date',
    dataType: 'date',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 10,
    visibleWhen: { personType: ['INDIVIDUAL'] },
    description: 'Data de vencimento da CNH do cliente.',
    businessImpact: 'Permite uso futuro em alertas e operacoes que dependam de habilitacao valida.',
  },
  {
    fieldKey: 'profile.cnpj',
    label: 'CNPJ',
    section: 'profile',
    required: true,
    importance: 'HIGH',
    inputType: 'document',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 11,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Documento principal da pessoa juridica.',
    businessImpact: 'Usado como identificador unico da empresa e para buscas por documento.',
    mask: 'cnpj',
  },
  {
    fieldKey: 'profile.corporateName',
    label: 'Razao Social',
    section: 'profile',
    required: true,
    importance: 'HIGH',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 12,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Nome formal da empresa.',
    businessImpact: 'Principal identificador textual do cliente PJ no sistema.',
  },
  {
    fieldKey: 'profile.tradeName',
    label: 'Nome Fantasia',
    section: 'profile',
    required: true,
    importance: 'HIGH',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 13,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Nome comercial usado pela empresa.',
    businessImpact: 'Facilita reconhecimento da empresa nas telas e no atendimento.',
  },
  {
    fieldKey: 'profile.stateRegistration',
    label: 'Inscricao Estadual',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 14,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Inscricao estadual da empresa.',
    businessImpact: 'Complementa o cadastro fiscal para cenarios onde a informacao e exigida.',
  },
  {
    fieldKey: 'profile.municipalRegistration',
    label: 'Inscricao Municipal',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 15,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Inscricao municipal da empresa.',
    businessImpact: 'Apoia contexto fiscal e municipal quando a operacao exigir.',
  },
  {
    fieldKey: 'profile.suframaRegistration',
    label: 'Inscricao Suframa',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 16,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Inscricao SUFRAMA da empresa, quando aplicavel.',
    businessImpact: 'Importante apenas para empresas e operacoes que dependem desse registro.',
  },
  {
    fieldKey: 'profile.taxpayerType',
    label: 'Tipo de Contribuinte',
    section: 'profile',
    required: false,
    importance: 'MEDIUM',
    inputType: 'select',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 17,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Enquadramento do contribuinte da empresa.',
    businessImpact: 'Influencia contextos fiscais e futuras integracoes tributarias.',
    optionsSource: 'static:taxpayer-types',
  },
  {
    fieldKey: 'profile.openingDate',
    label: 'Data de Abertura',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'date',
    dataType: 'date',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 18,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Data de abertura da empresa.',
    businessImpact: 'Permite calcular a idade da empresa para exibicao e analises futuras.',
  },
  {
    fieldKey: 'profile.companySegment',
    label: 'Segmento da Empresa',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 19,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Segmento de atuacao da empresa.',
    businessImpact: 'Ajuda em filtros, campanhas e contextualizacao comercial.',
  },
  {
    fieldKey: 'profile.issWithheld',
    label: 'ISS Retido na Fonte',
    section: 'profile',
    required: false,
    importance: 'LOW',
    inputType: 'boolean',
    dataType: 'boolean',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 20,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Indica se o ISS e retido na fonte.',
    businessImpact: 'Afeta contexto fiscal da empresa e futuras integracoes tributarias.',
  },
  {
    fieldKey: 'core.active',
    label: 'Status Ativo',
    section: 'core',
    required: true,
    importance: 'MEDIUM',
    inputType: 'boolean',
    dataType: 'boolean',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 21,
    visibleWhen: null,
    description: 'Status operacional do cadastro.',
    businessImpact: 'Clientes inativos podem ser desconsiderados em fluxos operacionais e comerciais.',
  },
  {
    fieldKey: 'core.customerSince',
    label: 'Cliente Desde',
    section: 'core',
    required: false,
    importance: 'LOW',
    inputType: 'date',
    dataType: 'date',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 22,
    visibleWhen: null,
    description: 'Data em que o relacionamento comecou.',
    businessImpact: 'Ajuda em analises de tempo de relacionamento com o cliente.',
  },
  {
    fieldKey: 'core.classification',
    label: 'Classificacao do Cliente',
    section: 'core',
    required: false,
    importance: 'MEDIUM',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 23,
    visibleWhen: null,
    description: 'Classificacao comercial do cliente.',
    businessImpact: 'Pode orientar filtros, segmentacao comercial e visoes operacionais.',
  },
  {
    fieldKey: 'core.referralSource',
    label: 'Como Nos Conheceu',
    section: 'core',
    required: false,
    importance: 'HIGH',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 24,
    visibleWhen: null,
    description: 'Origem de captacao do cliente.',
    businessImpact: 'Suporta analises de marketing, indicacao e origem de conversao.',
  },
  {
    fieldKey: 'core.referralName',
    label: 'Quem e o Amigo',
    section: 'core',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 25,
    visibleWhen: null,
    description: 'Nome do amigo ou indicador associado ao cadastro.',
    businessImpact: 'Permite rastrear indicacoes sem obrigar relacionamento formal no banco.',
  },
  {
    fieldKey: 'core.allowsInvoice',
    label: 'Emitir Notas Fiscais',
    section: 'core',
    required: false,
    importance: 'MEDIUM',
    inputType: 'boolean',
    dataType: 'boolean',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 26,
    visibleWhen: null,
    description: 'Indica se o cliente opera com emissao de nota fiscal.',
    businessImpact: 'Influencia contextos fiscais e operacoes futuras de faturamento.',
  },
  {
    fieldKey: 'core.hasRestriction',
    label: 'Restricao',
    section: 'core',
    required: false,
    importance: 'MEDIUM',
    inputType: 'boolean',
    dataType: 'boolean',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 27,
    visibleWhen: null,
    description: 'Marca se existe alguma restricao associada ao cliente.',
    businessImpact: 'Pode ser usada para alertas de risco, credito ou validacoes futuras.',
  },
  {
    fieldKey: 'core.isFinalConsumer',
    label: 'Consumidor Final',
    section: 'core',
    required: false,
    importance: 'LOW',
    inputType: 'boolean',
    dataType: 'boolean',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 28,
    visibleWhen: null,
    description: 'Indica se o cliente e consumidor final.',
    businessImpact: 'Ajuda em regras comerciais e fiscais futuras.',
  },
  {
    fieldKey: 'core.isRuralProducer',
    label: 'Produtor Rural',
    section: 'core',
    required: false,
    importance: 'LOW',
    inputType: 'boolean',
    dataType: 'boolean',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 29,
    visibleWhen: null,
    description: 'Indica se o cliente se enquadra como produtor rural.',
    businessImpact: 'Pode influenciar regras fiscais e segmentacao futura.',
  },
  {
    fieldKey: 'core.notes',
    label: 'Observacao',
    section: 'core',
    required: false,
    importance: 'LOW',
    inputType: 'textarea',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 30,
    visibleWhen: null,
    description: 'Campo livre para observacoes do cadastro.',
    businessImpact: 'Permite registrar contexto operacional que nao cabe em campos estruturados.',
  },
  {
    fieldKey: 'financial.creditLimit',
    label: 'Credito Liberado',
    section: 'financial',
    required: false,
    importance: 'MEDIUM',
    inputType: 'currency',
    dataType: 'number',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 31,
    visibleWhen: null,
    description: 'Credito disponibilizado ao cliente.',
    businessImpact: 'Pode orientar analise de credito e limites de relacionamento.',
  },
  {
    fieldKey: 'financial.amountSpent',
    label: 'Valor Gasto',
    section: 'financial',
    required: false,
    importance: 'LOW',
    inputType: 'currency',
    dataType: 'number',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 32,
    visibleWhen: null,
    description: 'Valor gasto pelo cliente.',
    businessImpact: 'Apoia acompanhamento financeiro e historico comercial.',
  },
  {
    fieldKey: 'financial.balance',
    label: 'Saldo',
    section: 'financial',
    required: false,
    importance: 'LOW',
    inputType: 'currency',
    dataType: 'number',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 33,
    visibleWhen: null,
    description: 'Saldo associado ao cliente.',
    businessImpact: 'Pode ser usado em visoes financeiras e decisao operacional.',
  },
  {
    fieldKey: 'financial.consumedAmount',
    label: 'Valor Consumido',
    section: 'financial',
    required: false,
    importance: 'MEDIUM',
    inputType: 'currency',
    dataType: 'number',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 34,
    visibleWhen: null,
    description: 'Base financeira de consumo usada no calculo de lucratividade.',
    businessImpact: 'Afeta diretamente o valor e o percentual de lucratividade calculados pela API.',
  },
  {
    fieldKey: 'financial.costAmount',
    label: 'Valor de Custos',
    section: 'financial',
    required: false,
    importance: 'MEDIUM',
    inputType: 'currency',
    dataType: 'number',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 35,
    visibleWhen: null,
    description: 'Base de custo usada no calculo de lucratividade.',
    businessImpact: 'Afeta diretamente o valor e o percentual de lucratividade calculados pela API.',
  },
  {
    fieldKey: 'financial.commissionPercentage',
    label: 'Comissao % por Indicacao',
    section: 'financial',
    required: false,
    importance: 'LOW',
    inputType: 'number',
    dataType: 'number',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 36,
    visibleWhen: null,
    description: 'Percentual de comissao vinculado a indicacao do cliente.',
    businessImpact: 'Pode apoiar regras comerciais e calculos futuros de comissao.',
  },
  {
    fieldKey: 'financial.paymentDay',
    label: 'Dia de Pagamento',
    section: 'financial',
    required: false,
    importance: 'LOW',
    inputType: 'number',
    dataType: 'number',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 37,
    visibleWhen: null,
    description: 'Dia preferencial de pagamento do cliente.',
    businessImpact: 'Apoia fluxos financeiros, cobranca e organizacao de vencimentos.',
  },
  {
    fieldKey: 'financial.pixKeyOrDescription',
    label: 'Dados do Pix',
    section: 'financial',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 38,
    visibleWhen: null,
    description: 'Chave Pix ou informacao relacionada a pagamentos.',
    businessImpact: 'Apoia recebimentos e referencia operacional do cliente.',
  },
  {
    fieldKey: 'computed.profitabilityAmount',
    label: 'Valor de Lucratividade',
    section: 'financial',
    required: false,
    importance: 'MEDIUM',
    inputType: 'currency',
    dataType: 'number',
    multiple: false,
    computed: true,
    readOnly: true,
    order: 39,
    visibleWhen: null,
    description: 'Diferenca calculada entre valor consumido e valor de custo.',
    businessImpact: 'Mostra o ganho absoluto associado ao cliente com base nos dados informados.',
  },
  {
    fieldKey: 'computed.profitabilityPercentage',
    label: 'Lucratividade %',
    section: 'financial',
    required: false,
    importance: 'MEDIUM',
    inputType: 'number',
    dataType: 'number',
    multiple: false,
    computed: true,
    readOnly: true,
    order: 40,
    visibleWhen: null,
    description: 'Percentual de lucratividade calculado pela API.',
    businessImpact: 'Mostra o retorno relativo do cliente e evita calculo manual no frontend.',
  },
  {
    fieldKey: 'address.zipCode',
    label: 'CEP',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'document',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 41,
    visibleWhen: null,
    description: 'CEP do endereco principal.',
    businessImpact: 'Apoia localizacao e integracao futura com busca de endereco.',
    mask: 'cep',
  },
  {
    fieldKey: 'address.street',
    label: 'Endereco Completo',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 42,
    visibleWhen: null,
    description: 'Logradouro do endereco principal.',
    businessImpact: 'Compoe a referencia principal de localizacao do cliente.',
  },
  {
    fieldKey: 'address.number',
    label: 'Numero',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 43,
    visibleWhen: null,
    description: 'Numero do endereco.',
    businessImpact: 'Complementa a localizacao detalhada do cliente.',
  },
  {
    fieldKey: 'address.complement',
    label: 'Complemento',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 44,
    visibleWhen: null,
    description: 'Complemento do endereco.',
    businessImpact: 'Melhora a precisao da localizacao do cadastro.',
  },
  {
    fieldKey: 'address.district',
    label: 'Bairro',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 45,
    visibleWhen: null,
    description: 'Bairro do endereco principal.',
    businessImpact: 'Apoia localizacao e filtros geograficos futuros.',
  },
  {
    fieldKey: 'address.city',
    label: 'Cidade',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 46,
    visibleWhen: null,
    description: 'Cidade em texto livre.',
    businessImpact: 'Apoia localizacao e futuras analises geograficas.',
  },
  {
    fieldKey: 'address.state',
    label: 'Estado',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 47,
    visibleWhen: null,
    description: 'Estado em texto livre.',
    businessImpact: 'Apoia localizacao e filtros regionais futuros.',
  },
  {
    fieldKey: 'address.cityCode',
    label: 'Codigo Cidade',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 48,
    visibleWhen: null,
    description: 'Codigo opcional da cidade.',
    businessImpact: 'Suporta integracoes futuras que dependam de codigos externos.',
  },
  {
    fieldKey: 'address.stateCode',
    label: 'Codigo Estado',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 49,
    visibleWhen: null,
    description: 'Codigo opcional do estado.',
    businessImpact: 'Suporta integracoes futuras que dependam de codigos externos.',
  },
  {
    fieldKey: 'address.reference',
    label: 'Referencia',
    section: 'address',
    required: false,
    importance: 'LOW',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 50,
    visibleWhen: null,
    description: 'Ponto de referencia do endereco.',
    businessImpact: 'Ajuda localizacao e operacao de atendimento.',
  },
  {
    fieldKey: 'contacts',
    label: 'Contatos',
    section: 'contacts',
    required: false,
    importance: 'HIGH',
    inputType: 'collection',
    dataType: 'array',
    multiple: true,
    computed: false,
    readOnly: false,
    order: 51,
    visibleWhen: null,
    description: 'Colecao de telefones, celulares ou contatos de mensagem.',
    businessImpact: 'Permite multiplos canais de contato sem engessar o cadastro em um unico telefone.',
  },
  {
    fieldKey: 'emails',
    label: 'Emails',
    section: 'emails',
    required: false,
    importance: 'HIGH',
    inputType: 'collection',
    dataType: 'array',
    multiple: true,
    computed: false,
    readOnly: false,
    order: 52,
    visibleWhen: null,
    description: 'Colecao de e-mails do cliente.',
    businessImpact: 'Permite multiplos canais digitais e uso futuro em comunicacao e notificacao.',
  },
  {
    fieldKey: 'communicationPreferences',
    label: 'Preferencias de Comunicacao',
    section: 'communicationPreferences',
    required: false,
    importance: 'MEDIUM',
    inputType: 'collection',
    dataType: 'array',
    multiple: true,
    computed: false,
    readOnly: false,
    order: 53,
    visibleWhen: null,
    description: 'Lista de permissao de envio por canal e assunto.',
    businessImpact: 'Evita disparos indevidos e centraliza consentimentos operacionais.',
  },
  {
    fieldKey: 'responsibles',
    label: 'Responsaveis',
    section: 'responsibles',
    required: true,
    importance: 'HIGH',
    inputType: 'collection',
    dataType: 'array',
    multiple: true,
    computed: false,
    readOnly: false,
    order: 54,
    visibleWhen: { personType: ['COMPANY'] },
    description: 'Colecao de responsaveis vinculados ao cliente PJ.',
    businessImpact: 'Cliente PJ precisa manter ao menos um responsavel para que o cadastro seja valido.',
  },
];

const responsibleSections: SectionConfig[] = [
  {
    key: 'profile',
    label: 'Dados do Responsavel',
    description: 'Dados pessoais e de identificacao do responsavel.',
    order: 1,
  },
  {
    key: 'address',
    label: 'Endereco',
    description: 'Endereco principal do responsavel.',
    order: 2,
  },
  {
    key: 'contacts',
    label: 'Contatos',
    description: 'Colecao de contatos do responsavel.',
    order: 3,
  },
  {
    key: 'emails',
    label: 'Emails',
    description: 'Colecao de e-mails do responsavel.',
    order: 4,
  },
];

const responsibleFields: FieldConfig[] = [
  {
    fieldKey: 'fullName',
    label: 'Nome Completo',
    section: 'profile',
    required: true,
    importance: 'HIGH',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 1,
    visibleWhen: null,
    description: 'Nome completo do responsavel.',
    businessImpact: 'Principal identificador textual do responsavel no sistema.',
  },
  {
    fieldKey: 'birthDate',
    label: 'Data de Nascimento',
    section: 'profile',
    required: false,
    importance: 'HIGH',
    inputType: 'date',
    dataType: 'date',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 2,
    visibleWhen: null,
    description: 'Data de nascimento do responsavel.',
    businessImpact: 'Permite exibir idade calculada e contextualizar o cadastro.',
  },
  {
    fieldKey: 'familyRelationship',
    label: 'Relacao Familiar',
    section: 'profile',
    required: false,
    importance: 'HIGH',
    inputType: 'text',
    dataType: 'string',
    multiple: false,
    computed: false,
    readOnly: false,
    order: 3,
    visibleWhen: null,
    description: 'Relacao familiar registrada para o responsavel.',
    businessImpact: 'Ajuda a explicar o papel do responsavel no relacionamento.',
  },
  {
    fieldKey: 'contacts',
    label: 'Contatos',
    section: 'contacts',
    required: false,
    importance: 'HIGH',
    inputType: 'collection',
    dataType: 'array',
    multiple: true,
    computed: false,
    readOnly: false,
    order: 4,
    visibleWhen: null,
    description: 'Colecao de contatos do responsavel.',
    businessImpact: 'Permite multiplos canais de contato com o responsavel.',
  },
  {
    fieldKey: 'emails',
    label: 'Emails',
    section: 'emails',
    required: false,
    importance: 'HIGH',
    inputType: 'collection',
    dataType: 'array',
    multiple: true,
    computed: false,
    readOnly: false,
    order: 5,
    visibleWhen: null,
    description: 'Colecao de e-mails do responsavel.',
    businessImpact: 'Permite multiplos canais digitais para contato com o responsavel.',
  },
];

export const customerFormMetadataDefaults: FormConfiguration = {
  formKey: 'customers-form',
  entity: 'customer',
  version: '1.2.0',
  sections: customerSections,
  fields: customerFields,
};

export const responsibleFormMetadataDefaults: FormConfiguration = {
  formKey: 'responsibles-form',
  entity: 'responsible',
  version: '1.2.0',
  sections: responsibleSections,
  fields: responsibleFields,
};

export const filterFieldsByPersonType = (fields: FieldConfig[], personType?: PersonType) =>
  fields.filter((field) => {
    if (!personType || !field.visibleWhen?.personType) {
      return true;
    }

    return field.visibleWhen.personType.includes(personType);
  });

export const groupFieldsBySections = (sections: SectionConfig[], fields: FieldConfig[]) =>
  sections
    .filter((section) => fields.some((field) => field.section === section.key))
    .sort((left, right) => left.order - right.order)
    .map((section) => ({
      section,
      fields: fields
        .filter((field) => field.section === section.key)
        .sort((left, right) => left.order - right.order),
    }));
